name: Build ESPRESSOBin Debian Image

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Free up disk space
      run: |
        sudo apt-get clean
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
        df -h

    - name: Build complete image
      run: |
        make build

    - name: Check output files
      run: |
        ls -la output/
        du -sh output/*

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: espressobin-debian-image
        path: |
          output/espressobin-debian.img.gz
          output/espressobin-debian.img.sha256
          output/espressobin-debian.img.gz.sha256
          output/FLASH_INSTRUCTIONS.txt
        retention-days: 30

    - name: Upload to release (if release)
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: output/espressobin-debian.img.gz
        asset_name: espressobin-debian-${{ github.event.release.tag_name }}.img.gz
        asset_content_type: application/gzip

  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: espressobin-debian-image
        path: output/

    - name: Verify checksums
      run: |
        cd output/
        sha256sum -c espressobin-debian.img.gz.sha256
        
    - name: Basic image validation
      run: |
        cd output/
        # Check if image is a valid gzip file
        gunzip -t espressobin-debian.img.gz
        echo "Image validation passed"